# Global Variables

title: More Tongues Than Teeth
description: New music video, "Safety First," out now!
keywords:
  - band
  - music
  - rock
  - indie rock
  - Brooklyn
logo:
  svg:
    black: "/assets/logo-black.svg"
    white: "/assets/logo-white.svg"
  png: "/assets/logo.png"
og_image: "/assets/og-image-02.jpg"
press_photos:
  - "/assets/pro-pic-2.jpg"
  - "/assets/fb-header.jpg"
  - "/assets/tour-poster-ig.jpg"
  - "/assets/Safety-First-3.jpg"
  - "/assets/tt-header.jpg"
  - "/assets/temper-tantrum-front-cover.jpg"
baseurl: ""
url: "https://www.moretongues.com"
fb_page_id: "169341510228289"
contact:
  facebook: "https://www.facebook.com/MoreTonguesThanTeeth/"
  instagram: "https://www.instagram.com/moretonguesthanteeth"
  bandcamp: "https://moretongues.bandcamp.com/releases"
  youtube: "https://www.youtube.com/channel/UCXUKrkDX88zx1bL4Xu8qZYw"
  email: "moretonguesthanteeth@gmail.com"
temper_tantrum:
  bandcamp: "https://moretongues.bandcamp.com/album/temper-tantrum"
  apple_music: "https://geo.itunes.apple.com/us/album/temper-tantrum/1339448765?mt=1&app=music&itscg=30200&itsct=afftoolset_1"
  spotify: "https://open.spotify.com/album/2atIKJg8Z1BrjYpL4Wk56a"
emptyArray: []

person_height: 84


# Build settings

markdown: kramdown
permalink: /:title/
timezone: America/New_York
auto_scroll: false
bg_testing: false
include:
  - "_headers"
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "node_modules"
  - "gulpfile.js"
  - "assets/test"
